const express = require('express')
const app = express()
const http = require('http')
const server = http.createServer(app)
const logger = require('morgan')
const cors = require('cors')
const multer = require('multer')
const passport = require('passport')
const io = require('socket.io')(server)
const chatSocket = require('./sockets/chat_socket')
const users = require('./routes/users_routes')
const chats = require('./routes/chats_routes')
const messages = require('./routes/messages_routes')
const port = process.env.PORT || 3000
app.use(logger('dev'))
app.use(express.json())
app.use(express.urlencoded({ extended: true }))
app.use(cors())
app.use(passport.initialize())
app.use(passport.session())
require('./config/passport')(passport)
app.disable('x-powered-by')
app.set('port', port)
chatSocket(io)
const upload = multer({ storage: multer.memoryStorage() })
users(app, upload)
chats(app)
messages(app, upload)
server.listen(3000, '192.168.0.50' || 'localhost', function () { console.log(`SERVER READY IN PORT ${port}`) })
app.use((err, req, res, next) => {
    console.log(err)
    res.status(err.status || 500).send(err.stack)
})
module.exports = { app: app, server: server }